site_name: Datapane Docs
repo_name: datapane/datapane
repo_url: https://github.com/datapane/datapane
copyright: © 2022 <a href="https://datapane.com" target="_blank">Datapane</a>. All rights reserved.

nav:
  - Overview: index.md
  - Concepts:
    - concepts/index.md
    - ""
  - Tutorials:
    - ""
  - Guides:
    - ""
  - Reference:
    - ""

theme:
  name: material
  logo: img/logo.png
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky
    #- navigation.expand

  #   - navigation.instant
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - mknotebooks
  - search:
      lang: en
  # Currently a sponsor-only feature
  # - social:
  #     cards_color:
  #       fill: "#131329"
  #       text: "#F2F2FD"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/datapane/datapane
    - icon: fontawesome/brands/discourse
      link: https://forum.datapane.com/
    - icon: fontawesome/brands/discord
      link: https://chat.datapane.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/datapaneapp
